### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by jdorfman** [IanDCarroll/xox#17]
Keep getting an error when trying to run test.

* System: 16.1.0 Darwin Kernel Version 16.1.0 (maxOS)
* Python: Python 2.7.11

```
 /tmp/xox > nosetests

Traceback (most recent call last):
  File "/usr/local/bin/nosetests", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'nose==1.1.2' distribution was not found and is required by the application
```

**Comment by jdorfman** [comment]
Just found out I needed to run `$ nosetests-2.7`

Might want to document that

**Comment by IanDCarroll** [comment]
Hmmm, I wonder if it's different between linux and macOS... I'll do some investigating.

**Comment by IanDCarroll** [comment]
Yeah, on my system, Ubuntu 16, `$ nosetests` does just fine. But so does `nosetests-2.7`. I'll just modify the README to work regardless.
